import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Network,Server,Router,HardDrive,Wifi,Monitor,LayoutDashboard,Cable,RefreshCw,Bell,Plus,Search,ChevronRight,ArrowUpRight,CalendarDays,LogOut,X,Trash2,Check,Lock,Menu} from 'lucide-react';
import {allocation,ipNumber,ipString} from './ip.mjs';
import './style.css';
type Device={id:string,name:string,model:string,type:string,ip:string,subnet_id:string,firmware:string,target:string,parent:string,due:string,status:string,location:string,notes:string};
type Subnet={id:string,name:string,cidr:string,gateway:string,vlan:number|null};
type Inventory={devices:Device[],subnets:Subnet[]};
type Session={username:string,csrf:string};
const kinds=['Router','Switch','Server','Storage','Access point','Computer'];
const icons:Record<string,typeof Server>={Router,Switch:Network,Server,Storage:HardDrive,'Access point':Wifi,Computer:Monitor};
const sections=[['Overview',LayoutDashboard],['Devices',Server],['Network map',Network],['IP plan',Cable],['Firmware',RefreshCw],['Reminders',Bell]] as const;
const emptyDevice:Device={id:'',name:'',model:'',type:'Server',ip:'',subnet_id:'',firmware:'',target:'',parent:'',due:'',status:'In service',location:'',notes:''};
const emptySubnet:Subnet={id:'',name:'',cidr:'192.168.1.0/24',gateway:'',vlan:null};
const needs=(d:Device)=>!!d.target&&d.target!==d.firmware;
const dateText=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function Dialog({title,children,onClose,busy=false}:{title:string,children:React.ReactNode,onClose:()=>void,busy?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);
 return <dialog ref={ref} className="dialog" onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><header><h2>{title}</h2><button className="icon-btn" disabled={busy} onClick={onClose} aria-label="Close dialog"><X/></button></header>{children}</dialog>;
}
function App(){
 const [session,setSession]=useState<Session|null>(null),[starting,setStarting]=useState(true),[inventory,setInventory]=useState<Inventory>({devices:[],subnets:[]}),[view,setView]=useState('Overview'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('All types'),[device,setDevice]=useState<Device|null>(null),[subnet,setSubnet]=useState<Subnet|null>(null),[deleteKind,setDeleteKind]=useState<'device'|'subnet'|null>(null),[sidebar,setSidebar]=useState(false),[loginName,setLoginName]=useState('admin'),[password,setPassword]=useState(''),[loaded,setLoaded]=useState(false);
 async function request(path:string,method='GET',body?:unknown,csrf=session?.csrf){
  let response:Response;try{response=await fetch('/api'+path,{method,credentials:'same-origin',headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)})}catch{throw Error('Cannot reach the server. Check your connection and try again.')}
  if(response.status===401&&path!='/login'){setSession(null);setLoaded(false);setDevice(null);setSubnet(null);setDeleteKind(null);}
  if(!response.ok){const data=await response.json().catch(()=>({error:'Request failed. Please try again.'}));throw Error(data.error||'Request failed. Please check the fields and try again.')}
  return response.status===204?null:response.json();
 }
 async function load(csrf?:string){setError('');try{setInventory(await request('/inventory','GET',undefined,csrf));setLoaded(true)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/session');if(r.ok){const s=await r.json();setSession(s);await load(s.csrf)}else if(r.status!==401){setError('Could not open your session. Reload the page to try again.')}}catch{setError('Cannot reach the server. Reload the page to try again.')}finally{setStarting(false)}})()},[]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(id)},[notice]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const s=await request('/login','POST',{username:loginName,password});setSession(s);setPassword('');await load(s.csrf)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{await request('/logout','POST');setSession(null);setInventory({devices:[],subnets:[]});setLoaded(false);setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function go(next:string){setView(next);setQuery('');setFilter('All types');setSidebar(false);setError('')}
 function openDevice(d:Device){setDevice({...d});setError('')}
 function openSubnet(s:Subnet){setSubnet({...s});setError('')}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{setInventory(await request(device?'/devices':'/subnets','POST',device||subnet));setDevice(null);setSubnet(null);setNotice('Changes saved')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(){setBusy(true);setError('');try{setInventory(await request(deleteKind==='device'?'/devices/'+device?.id:'/subnets/'+subnet?.id,'DELETE'));setDeleteKind(null);setDevice(null);setSubnet(null);setNotice('Deleted successfully')}catch(e){setDeleteKind(null);setError((e as Error).message)}finally{setBusy(false)}}
 const {devices,subnets}=inventory,updates=devices.filter(needs),reminders=devices.filter(d=>d.due).sort((a,b)=>a.due.localeCompare(b.due)),visible=devices.filter(d=>(filter==='All types'||d.type===filter)&&[d.name,d.model,d.ip].join(' ').toLowerCase().includes(query.toLowerCase()));
 function table(){return <div className="table-scroll"><table><thead><tr>{['Device','IP address','Status','Firmware','Location',''].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{visible.map(d=>{const Icon=icons[d.type];return <tr key={d.id}><td><button className="device-name" onClick={()=>openDevice(d)}><span className="device-icon"><Icon size={20}/></span><span><strong>{d.name}</strong><small>{d.model||d.type}</small></span></button></td><td className="mono">{d.ip||'Unassigned'}</td><td><span className={'status '+(d.status==='Powered off'?'off':'')}>{d.status}</span></td><td className="mono">{d.firmware||'Not recorded'}{needs(d)&&<span className="update-dot" title="Update planned"/>}</td><td className="muted">{d.location||'Not specified'}</td><td><button className="icon-btn" aria-label={'Edit '+d.name} onClick={()=>openDevice(d)}><ChevronRight size={17}/></button></td></tr>})}</tbody></table>{!visible.length&&<div className="empty"><Server/>{devices.length?'No devices match your search.':'Add your first device to start your inventory.'}</div>}</div>}
 function graph(){
  if(!devices.length)return <div className="empty"><Network/>Your network starts with a device.<button className="text-button" onClick={()=>openDevice({...emptyDevice})}>Add device</button></div>;
  const depth=(d:Device,seen:string[]=[]):number=>{const p=devices.find(x=>x.id===d.parent);return !p||seen.includes(d.id)?0:1+depth(p,[...seen,d.id])};
  const levels=[...new Set(devices.map(d=>depth(d)))].sort((a,b)=>a-b),max=Math.max(...levels.map(l=>devices.filter(d=>depth(d)===l).length)),width=Math.max(580,max*170),height=levels.length*145+30;
  const pos=new Map<string,{x:number,y:number}>();levels.forEach(l=>{const row=devices.filter(d=>depth(d)===l);row.forEach((d,i)=>pos.set(d.id,{x:width/(row.length+1)*(i+1),y:l*145+20}))});
  return <div className="network-canvas" tabIndex={0} aria-label="Network topology, scroll to explore"><div className="graph" style={{width,height}}><svg width={width} height={height} aria-label="Device connections">{devices.filter(d=>pos.has(d.parent)).map(d=>{const a=pos.get(d.parent)!,b=pos.get(d.id)!;return <path key={d.id} d={`M ${a.x} ${a.y+100} V ${a.y+122} H ${b.x} V ${b.y}`} fill="none" stroke="#90b59f" strokeWidth="1.5"><title>{devices.find(x=>x.id===d.parent)?.name} to {d.name}</title></path>})}</svg>{devices.map(d=>{const p=pos.get(d.id)!,Icon=icons[d.type];return <button key={d.id} className={'network-node '+(needs(d)?'has-update':'')} style={{left:p.x-74,top:p.y}} onClick={()=>openDevice(d)}><Icon size={23}/><strong>{d.name}</strong><code>{d.ip||'No IP assigned'}</code></button>})}</div><p className="map-caption">Recorded connections · select a device to edit its parent</p></div>
 }
 const errorBox=error&&<div className="error" role="alert">{error}{session&&!device&&!subnet&&<button onClick={()=>load()}>Retry</button>}</div>;
 if(starting)return <div className="login-shell"><p>Opening your lab…</p></div>;
 if(!session)return <div className="login-shell"><form className="login-card" onSubmit={login}><div className="brand"><span className="brand-mark"><Network/></span><span>homelab<small>MANAGER</small></span></div><h1>Welcome to your lab</h1><p className="muted">Sign in to manage your home infrastructure.</p>{errorBox}<label>Username<input autoComplete="username" value={loginName} onChange={e=>setLoginName(e.target.value)} required maxLength={100}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={256}/></label><button className="primary" disabled={busy}><Lock size={16}/>{busy?'Signing in…':'Sign in'}</button><small className="muted">Use the account created with homelab init.</small></form></div>;
 return <><aside className={'sidebar '+(sidebar?'mobile-open':'')}><div className="brand"><span className="brand-mark"><Network/></span><span>homelab<small>MANAGER</small></span></div><div className="workspace-label">WORKSPACE</div><nav>{sections.map(([name,Icon])=><button key={name} className={'nav-button '+(name===view?'active':'')} onClick={()=>go(name)}><Icon size={19}/>{name}{name==='Firmware'&&updates.length>0&&<span className="nav-count">{updates.length}</span>}</button>)}</nav><div className="side-note"><Server/><strong>Small lab.<br/>Endless possibilities.</strong><p>A place for every device.</p></div><div className="profile"><span className="avatar">HL</span><div><strong>{session.username}</strong><small>Personal workspace</small></div><button className="icon-btn" disabled={busy} onClick={logout} aria-label="Sign out"><LogOut size={18}/></button></div></aside>{sidebar&&<button className="sidebar-backdrop" aria-label="Close navigation" onClick={()=>setSidebar(false)}/>}
 <main className="main"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-btn" aria-label="Toggle navigation" onClick={()=>setSidebar(!sidebar)}><Menu/></button>My lab<ChevronRight size={14}/><strong>{view}</strong></div><div className="top-right"><span>HOME LAB</span><button className="icon-btn" aria-label="Open reminders" onClick={()=>go('Reminders')}><Bell size={20}/></button><span className="avatar">HL</span></div></header><div className="workspace"><div className="page-heading"><div className="heading-copy"><div className="eyebrow">YOUR INFRASTRUCTURE, AT A GLANCE</div><h1>{view==='Overview'?'Lab overview':view}</h1><p>{view==='Overview'?'Your devices, connections, and updates. All in one place.':view==='IP plan'?'Subnets, assigned addresses, and available space.':view==='Reminders'?'Your maintenance schedule. Reminders appear here while the app is open.':view==='Firmware'?'Installed and target versions recorded by you.':'Your home infrastructure, organized.'}</p></div><button className="primary" disabled={!loaded} onClick={()=>view==='IP plan'?openSubnet({...emptySubnet}):openDevice({...emptyDevice})}><Plus size={18}/>{view==='IP plan'?'Add subnet':'Add device'}</button></div>{!device&&!subnet&&errorBox}
 {!loaded&&!error&&<div className="empty">Loading inventory…</div>}
 {loaded&&<>{view==='Overview'&&<><div className="stats">{[[Server,'Total devices',devices.length,'In your lab'],[Network,'Subnets',subnets.length,'Defined address ranges'],[RefreshCw,'Updates planned',updates.length,'Target version recorded'],[CalendarDays,'Reminders',reminders.length,'Scheduled by you']].map(([Icon,label,value,sub]:any)=><section className="stat" key={label}><div><span>{label}</span><Icon size={20}/></div><strong>{value}</strong><p>{sub}</p></section>)}</div><div className="overview-grid"><section className="panel"><div className="panel-head"><h2>Network map <span className="pill">Topology</span></h2><button className="text-button" onClick={()=>go('Network map')}>Open map <ArrowUpRight size={16}/></button></div>{graph()}</section><section className="panel"><div className="panel-head"><h2>Updates <span className="count">{updates.length}</span></h2><RefreshCw size={18}/></div><div className="updates-list">{updates.slice(0,3).map(d=><button className="update-item" key={d.id} onClick={()=>openDevice(d)}><strong>{d.name}</strong><small>{d.model||d.type}</small><p><code>{d.firmware||'Not recorded'}</code> → <code className="target">{d.target}</code></p><small><CalendarDays size={14}/>{d.due?dateText(d.due):'No date set'}</small></button>)}{!updates.length&&<div className="empty"><Check/>No updates planned.</div>}</div><button className="panel-bottom" onClick={()=>go('Firmware')}>All firmware <ArrowUpRight size={16}/></button></section></div></>}
 {(view==='Overview'||view==='Devices')&&<section className="panel"><div className="panel-head"><h2>Devices <span className="count">{devices.length}</span></h2><div className="table-tools"><label className="search"><Search size={16}/><input aria-label="Search devices" placeholder="Search devices or IP" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter device type" value={filter} onChange={e=>setFilter(e.target.value)}>{['All types',...kinds].map(t=><option key={t}>{t}</option>)}</select></div></div>{table()}</section>}
 {view==='Network map'&&<section className="panel full-map">{graph()}</section>}
 {view==='IP plan'&&<><div className="subnet-cards">{subnets.map(s=>{const a=allocation(s,devices)!;const ipDevices=devices.filter(d=>{const n=ipNumber(d.ip);return n!==null&&n>=a.first&&n<=a.last});return <section className="panel subnet" key={s.id}><div className="panel-head"><h2>{s.name}</h2><button className="text-button" onClick={()=>openSubnet(s)}>Edit</button></div><div className="subnet-body"><strong className="cidr">{s.cidr}</strong><p>{a.used.toLocaleString()} reserved / assigned · {a.free.toLocaleString()} available</p><p>Gateway: {s.gateway||'Not set'} · VLAN: {s.vlan??'None'}</p><div className="ip-grid">{Array.from({length:Math.min(a.total,256)},(_,i)=>{const n=a.first+i,ip=ipString(n),d=devices.find(x=>x.ip===ip);return <button key={n} className={a.assigned.has(n)?'occupied':''} aria-label={ip+(d?' '+d.name:ip===s.gateway?' gateway':' available')} title={ip+(d?' · '+d.name:ip===s.gateway?' · gateway':' · available')} onClick={()=>d?openDevice(d):openDevice({...emptyDevice,ip,subnet_id:s.id})}/>})}</div><small>{a.total>256?'First 256 usable addresses shown. ':''}Gateway is reserved even without a device.</small><button className="text-button" disabled={!a.next} onClick={()=>openDevice({...emptyDevice,ip:a.next||'',subnet_id:s.id})}>Allocate next IP {a.next&&<code>{a.next}</code>}</button>{ipDevices.length>0&&<div className="subnet-devices">{ipDevices.map(d=><button key={d.id} onClick={()=>openDevice(d)}><span>{d.name}</span><code>{d.ip}</code></button>)}</div>}</div></section>})}</div>{!subnets.length&&<section className="panel empty"><Cable/>Add a subnet using CIDR notation, such as 10.0.3.80/28.</section>}<section className="panel"><div className="panel-head"><h2>Device addresses</h2></div>{table()}</section></>}
 {view==='Firmware'&&<section className="panel table-scroll"><table><thead><tr>{['Device','Installed','Target','State',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{devices.map(d=><tr key={d.id}><td><strong>{d.name}</strong><small className="block muted">{d.model}</small></td><td className="mono">{d.firmware||'Not recorded'}</td><td className="mono">{d.target||'Not recorded'}</td><td><span className={'status '+(needs(d)?'warning':'')}>{needs(d)?'Update planned':d.target?'Versions match':'Not checked'}</span></td><td><button className="text-button" onClick={()=>openDevice(d)}>Edit <ChevronRight size={15}/></button></td></tr>)}</tbody></table>{!devices.length&&<div className="empty">Add a device to track firmware.</div>}</section>}
 {view==='Reminders'&&<section className="panel"><div className="panel-head"><h2>Maintenance schedule</h2><span className="muted">In-app reminders</span></div>{reminders.map(d=><button className="reminder" key={d.id} onClick={()=>openDevice(d)}><div className="date-tile"><strong>{d.due.slice(8)}</strong><span>{new Date(d.due+'T12:00:00').toLocaleDateString('en-US',{month:'short'})}</span></div><div><strong>Check for updates · {d.name}</strong><p>{dateText(d.due)} · {d.firmware||'Version not recorded'}{d.target?' → '+d.target:''}</p></div><span className={'status '+(d.due<=today()?'warning':'')}>{d.due<today()?'Overdue':d.due===today()?'Due today':'Scheduled'}</span><ChevronRight size={18}/></button>)}{!reminders.length&&<div className="empty"><CalendarDays/>Set a check date in a device card to add a reminder.</div>}</section>}</>}
 <footer className="footer"><span><Network size={15}/> Home Lab Manager · v0.1.0</span><span>Inventory data · manually maintained</span></footer></div></main>
 {notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
 {device&&<Dialog title={device.id?'Device details':'New device'} onClose={()=>{setDevice(null);setError('')}} busy={busy}><form onSubmit={save}><div className="form-grid">{[['name','Device name'],['model','Model'],['ip','IPv4 address'],['location','Location'],['firmware','Installed version'],['target','Target version']].map(([key,label])=><label key={key}>{label}<input autoFocus={key==='name'} required={key==='name'} maxLength={key==='name'?100:200} value={device[key as keyof Device]} onChange={e=>setDevice({...device,[key]:e.target.value})}/></label>)}<label>Type<select value={device.type} onChange={e=>setDevice({...device,type:e.target.value})}>{kinds.map(k=><option key={k}>{k}</option>)}</select></label><label>Status<select value={device.status} onChange={e=>setDevice({...device,status:e.target.value})}>{['In service','Powered off','Maintenance'].map(s=><option key={s}>{s}</option>)}</select></label><label>Subnet<select value={device.subnet_id} onChange={e=>setDevice({...device,subnet_id:e.target.value})}><option value="">Unassigned</option>{subnets.map(s=><option key={s.id} value={s.id}>{s.name} · {s.cidr}</option>)}</select></label><label>Connected to<select value={device.parent} onChange={e=>setDevice({...device,parent:e.target.value})}><option value="">None / root device</option>{devices.filter(d=>d.id!==device.id).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Next check date<input type="date" min="0001-01-01" max="9999-12-31" value={device.due} onChange={e=>setDevice({...device,due:e.target.value})}/></label><label className="wide">Notes<textarea rows={3} maxLength={4000} value={device.notes} onChange={e=>setDevice({...device,notes:e.target.value})}/></label></div>{errorBox}<div className="form-actions">{device.id&&<button type="button" className="danger" disabled={busy} onClick={()=>setDeleteKind('device')}><Trash2 size={16}/>Delete</button>}<button type="button" className="secondary" disabled={busy} onClick={()=>{setDevice(null);setError('')}}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save device'}</button></div></form></Dialog>}
 {subnet&&<Dialog title={subnet.id?'Subnet details':'New subnet'} onClose={()=>{setSubnet(null);setError('')}} busy={busy}><form onSubmit={save}><div className="form-grid"><label>Name<input autoFocus required maxLength={100} value={subnet.name} onChange={e=>setSubnet({...subnet,name:e.target.value})}/></label><label>IPv4 CIDR<input required placeholder="10.0.3.80/28" value={subnet.cidr} onChange={e=>setSubnet({...subnet,cidr:e.target.value})}/></label><label>Gateway<input value={subnet.gateway} onChange={e=>setSubnet({...subnet,gateway:e.target.value})}/></label><label>VLAN (optional)<input type="number" min={1} max={4094} value={subnet.vlan??''} onChange={e=>setSubnet({...subnet,vlan:e.target.value?Number(e.target.value):null})}/></label></div><p className="muted">Use a network address with a /0–/32 prefix. Overlapping subnets are not supported in this version.</p>{errorBox}<div className="form-actions">{subnet.id&&<button type="button" className="danger" disabled={busy} onClick={()=>setDeleteKind('subnet')}><Trash2 size={16}/>Delete</button>}<button type="button" className="secondary" disabled={busy} onClick={()=>{setSubnet(null);setError('')}}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save subnet'}</button></div></form></Dialog>}
 {deleteKind&&<Dialog title={'Delete '+(deleteKind==='device'?device?.name:subnet?.name)+'?'} onClose={()=>setDeleteKind(null)} busy={busy}><p>{deleteKind==='device'?'Connected devices will remain, but their parent connection will be cleared.':'A subnet can only be deleted after its assigned devices have been moved out.'}</p><div className="form-actions"><button className="secondary" disabled={busy} onClick={()=>setDeleteKind(null)}>Cancel</button><button className="primary destructive" disabled={busy} onClick={remove}>{busy?'Deleting…':'Delete'}</button></div></Dialog>}
 </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
